.TH PF2XML 3 "$Date$"
.SH NAME
pf2xml \- Convert a parameter-file to XML
.SH SYNOPSIS
.nf
#include "pfxml.h"

char *pf2xml( Pf *pf, char *name, char *prolog, int flags )
.fi
.SH DESCRIPTION
pf2xml converts an Antelope parameter-file to a string which contains an eXtensible 
Markup Language (XML) translation of the information in the parameter file. 
The 'name' parameter specifies the name for the top-level element.  This 
argument must be non-zero and non-empty. The prolog argument specifies
an optional header to be placed on the string in front of the converted
parameter-file values. To omit the prolog, this argument should be set
to 0. The flags argument may be 0 for default conversion, or may specify
one or more conversion options (multiple options may be specified by 
combining them with the binary 'OR' operator). Conversion errors result
in a null value being returned.

If flags is set to PFXML_NEWLINES, newlines are added after tags 
and values. Otherwise the return value is one long string without 
embedded newlines (unless there are any explicit newlines in the parameter 
file, for example from a &Literal parameter). 

If flags is set to PFXML_PRESERVE_PFFILE, elements of type 'pffile' are 
preserved as such. Without this flag (i.e. the default behavior), they are
recast into elements of type 'pfarr'. This remapping allows a parameter file 
to be included in another parameter-file as a sub-component.

Currently, two output modes for pf2xml are defined. The default mode is
the 'weak' conversion mode. If the flags argument is set to PFXML_STRONG, 
the 'strong' conversion mode is used. 

In the weak conversion mode, four tags are defined, those being pffile, 
pfarr, pftbl, and pfstring. All parameter-file elements will be converted 
to an element with one of these four tags. If the parameter-file parameter 
has a name (which is the case for everything except &Tbl entries), that name
will be included as a 'name' attribute of the tag [For more information on 
the distinctions between elements, tags, and their attributes, see any 
standard documentation on XML]. 

In the 'strong' conversion mode (obtained by setting flags to PFXML_STRONG),
each parameter-file entity is converted to an element with name the 
same as the parameter name. (The parameter-file object type of pfstring,
pffile, pfarr, or pftbl is given as an attribute of the tag). 
In the strong mode it is not possible for children of a pftbl element 
to be anonymous, so these elements are given the tag pftbl_entry.

.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.ft CW
.in 2c
.nf
weak mode:

<pfstring name="myparam">An interesting string</pfstring>

strong mode:

<myparam type="pfstring">An interesting string</myparam> 
.fi
.in
.ft R
.SH RETURN VALUES
pf2xml returns a newly allocated character string with the XML
value, or a NULL string on error. This string must be 
freed by the calling program.
.SH LIBRARY
.SH ATTRIBUTES
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
pf2xml(1), pf(3), pf(5)
.fi
.SH "BUGS AND CAVEATS"
No indentation is supported. 

Only one simplistic output format is supported.
.SH AUTHOR
.nf
Kent Lindquist
Lindquist Consulting, Inc.
.fi
.\" $Id$
