.TH REFGUIDE 1 "$Date$"
.SH NAME
refguide \- prepare a Framemaker mif version of a reference guide
.SH SYNOPSIS
.nf
refguide {c|user|scripting}
.fi
.SH DESCRIPTION
\fBrefguide\fR runs \fbtxform\fR(1) to create a Framemaker
mif format reference guide.  Currently, there are the following
different reference guides:
.IP user
This covers Antelope command line programs.
.IP c
The c reference covers the c interfaces.
.IP scripting
This covers the various scripting languages which can 
be used with Antelope: tcl/tk, perl and matlab.
.SH FILES
The ascii input files which are used to create the
Framemaker output are kept in $ANTELOPE/data/refguides.
The output is a file named 
\fIc.mif\fR,
\fIuser.mif\fR or
\fIscripting.mif\fR.
.SH EXAMPLE
.ft CW
.RS .2i
refguide user
.RE
.ft R
.SH "SEE ALSO"
.nf
txform(1)
.fi
.SH "BUGS AND CAVEATS"
The reference guides (particularly the c reference guide)
are deliberately incomplete in 
order to be less confusing and more useful.  Obsolete, 
deprecated, obscure, and redundant interfaces are typically
omitted, in order to concentrate on the important and useful
routines.  Considerably more detail is available in the
man pages.  The reference guides provide a more compact 
and accessible quick survey of capabilities.
.SH AUTHOR
.nf
Kent Lindquist
Daniel Quinlan
.\" $Id$
