DATADIR= matlab/antelope/scripts
DATA= \
	setup_antelope.m \
	array_response.m \
	tr2struct.m 

HTMLDIR= matlab/antelope/html
HTML= $(DATA:.m=.html)

CLEAN= 

include $(ANTELOPE)/include/mex_antelope_makerules
