DATADIR=instruments/dataloggers
DATA= hrd24.pf \
    hrd24_iir.pf \
    taurus_inf.pf \
    taurus_inf_08V_swg1.pf \
    taurus_inf_08V_swg1_iir0_001.pf \
    taurus_inf_40V_swg1.pf \
    taurus_inf_40V_swg1_iir0_001.pf \
    taurus_std.pf \
    taurus_std.pf \
    taurus_std.pf \
    taurus_std_40V_swg1.pf \
    taurus_std_40V_swg1_iir0_001.pf \
    trident.pf 

include $(ANTELOPEMAKE)
DIRS=
