DATADIR=instruments/dataloggers
DATA= hrd24.pf \
    hrd24_iir.pf \
    taurus01_hi_02V_swg1_iir0_001.pf \
    taurus02_hi_02V_swg1_iiroff.pf \
    taurus03_lo_02V_swg1_iir0_001.pf \
    taurus04_lo_02V_swg1_iiroff.pf \
    taurus05_hi_04V_swg1_iir0_001.pf \
    taurus06_hi_04V_swg1_iiroff.pf \
    taurus07_lo_04V_swg1_iir0_001.pf \
    taurus08_lo_04V_swg1_iiroff.pf \
    taurus09_hi_08V_swg1_iir0_001.pf \
    taurus10_hi_08V_swg1_iiroff.pf \
    taurus11_lo_08V_swg1_iir0_001.pf \
    taurus12_lo_08V_swg1_iiroff.pf \
    taurus13_hi_16V_swg1_iir0_001.pf \
    taurus14_hi_16V_swg1_iiroff.pf \
    taurus15_lo_16V_swg1_iir0_001.pf \
    taurus16_lo_16V_swg1_iiroff.pf \
    taurus17_hi_40V_swg1_iir0_001.pf \
    taurus18_hi_40V_swg1_iiroff.pf \
    taurus19_lo_40V_swg1_iir0_001.pf \
    taurus20_lo_40V_swg1_iiroff.pf \
    taurus_inf.pf \
    taurus_std.pf \
    trident.pf 

include $(ANTELOPEMAKE)
DIRS=
