DATADIR=instruments/dataloggers
DATA= hrd24.pf \
    hrd24_iir.pf \
    taurus09_hi_08V_swg1_iir0_001.pf \
    taurus10_hi_08V_swg1_iiroff.pf \
    taurus11_lo_08V_swg1_iir0_001.pf \
    taurus12_lo_08V_swg1_iiroff.pf \
    taurus17_hi_40V_swg1_iir0_001.pf \
    taurus18_hi_40V_swg1_iiroff.pf \
    taurus19_lo_40V_swg1_iir0_001.pf \
    taurus20_lo_40V_swg1_iiroff.pf \
    taurus_inf.pf \
    taurus_std.pf \
    trident.pf 

include $(ANTELOPEMAKE)
DIRS=
