1,$s/Database_Handle/DatabaseHandle/g
1,$s/Datascope_Handle/DatascopeHandle/g
1,$s/Metadata_list/MetadataList/g
1,$s/Attribute_Properties/AttributeProperties/g
1,$s/Attribute_Map/AttributeMap/g
1,$s/Metadata_error/MetadataError/g
1,$s/Metadata_get_error/MetadataGetError/g
1,$s/Metadata_parse_error/MetadataParseError/g
1,$s/Decimated_vector/DecimatedVector/g
1,$s/Resample_Operator/ResampleOperator/g
1,$s/Interval_Cmp/IntervalCompare/g
1,$s/Range_Cmp/RangeCompare/g
1,$s/Resampling_Definitions/ResamplingDefinitions/g
1,$s/seispp_error/SeisppError/g
1,$s/seispp_dberror/SeisppDberror/g
1,$s/SAC_data_error/SACdataError/g
1,$s/Slowness_vector/SlownessVector/g
1,$s/Rectangular_Slowness_Grid/RectangularSlownessGrid/g
1,$s/Time_Window/TimeWindow/g
1,$s/Time_Variable_Weight/TimeVariableWeight/g
1,$s/Time_Window_Cmp/TimeWindowCompare/g
1,$s/Basic_Time_Series/BasicTimeSeries/g
1,$s/Three_Component_Ensemble/ThreeComponentEnsemble/g
1,$s/Three_Component_Seismogram/ThreeComponentSeismogram/g
1,$s/Time_Series_Ensemble/TimeSeriesEnsemble/g
1,$s/Time_Series/TimeSeries/g
1,$s/Top_Mute/TopMute/g
1,$s/Velocity_Model_1d_error/VelocityModel_1d_Error/g
1,$s/Velocity_Model_1d_dberror/VelocityModel_1d_Dberror/g
1,$s/Velocity_Model_1d_ioerror/VelocityModel_1d_IOerror/g
1,$s/Velocity_Model_1d/VelocityModel_1d/g
1,$s/Resample_TimeSeries/ResampleTimeSeries/g
1,$s/put_metadata/put/g
1,$s/Extract_Component/ExtractComponent/g
1,$s/Spherical_Coordinate/SphericalCoordinate/g
1,$s/spherical_to_unit_vector/SphericalToUnitVector/g
1,$s/unit_vector_to_spherical/UnitVectorToSpherical/g
1,$s/pm_halfspace_model/PMHalfspaceModel/g
1,$s/set_gaps/SetGaps/g
1,$s/pfstream_save_3cseis/PfstreamSave3cseis/g
1,$s/get_next_3c_ensemble/GetNext3cEnsemble/g
1,$s/get_next_ensemble/GetNextEnsemble/g
1,$s/Load_TimeSeries_Using_Pf/LoadTimeSeriesUsingPf/g
1,$s/get_next_time_series/GetNextTimeSeries/g
1,$s/apply_geometric_static/ApplyGeometricStatic/g
1,$s/apply_top_mute/ApplyTopMute/g
1,$s/TimeSeries_Ensemble/TimeSeriesEnsemble/g
1,$s/error_severity/ErrorSeverity/g
1,$s/TimeWindow_Cmp/TimeWindowCmp/g
1,$s/Time_Reference_Type/TimeReferenceType/g
