'\" te
.TH METADATA_ERROR 3 "%G"
.SH NAME
MetadataError - Metadata object error facility
.SH SYNOPSIS
.nf
#include "Metadata.h"
using namespace SEISPP;
class MetadataError
class MetadataGetError : public MetadataError
class MetadataParseError : public MetadataError
.fi
.SH DESCRIPTION
.LP
The set of \fIMetadataError\fR objects are companions to 
the variable length header concept Metadata(3) object.  
Some of the metadata object functions will throw MetadataError
or the derived classes listed in the Synopsis.  Error 
handlers can be written to trap these exceptions using
real time type checking to sort out which actual type is
thrown (see classic books by Stoustrup or other books on
C++ for examples).  
.LP
A \fIMetadataError\fR is a generic error object that contains
little more than an error message that can be sent to stderr 
using a function called \fIlog_error()\fR.  
.LP
The derived classes \fIMetadataGetError\fR and 
\fIMetadataParseError\fR are more specific.  
A \fIMetadataGetError\fR may be thrown by any of 
the "get" metadata functions.  The most common reason
is that the parameter with the requested name either
did not exist in the metadata object or there was
a type mismatch.  The assumption is that a handler
need only know that the get process failed and it
should give the user feedback on why it might have
failed.  Hence, it contains only an extended message
facility to dump the error message using the \fIlog_error()\fR
function.  
.LP
The \fIMetadataParseError\fR function is implementation
specific.  The metadata object as currently defined uses
an Antelope Pf "object" to store the abstract concept 
I've called "metadata."  A \fIMetadataParseError\fR
is thrown by metadata constructors when a parameter file or
string used to build the Pf fails on a pfcompile error.
A \fIMetadataParseError\fR object thus contains the 
log_error() function plus an integer variable called
\fIerror_code\fR that contains the error code from pfcompile.
.SH LIBRARY
.LP
-lseispp
.SH "SEE ALSO"
.nf
TimeSeries(3),SeisppError(3),
http://geology.indiana.edu/pavlis/software/seispp/html/index.html
.fi
.SH "BUGS AND CAVEATS"
.LP
This is a fairly simple error object definition.  It might
evolve as time goes on.
.SH AUTHOR
.nf
Gary L. Pavlis
Indiana University
pavlis@indiana.edu
.fi
.\" $Id$
