.TH Fmfpfit 3P 
.SH NAME
Fmfpfit \- evproc class for computing focal-mechanisms with USGS fpfit
.SH SYNOPSIS
.nf
.fi
.SH DESCRIPTION
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
MT-Safe ?
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
The parameters \fIuse_radiation_pattern_weighting\fP and \fIperform_fine_search\fP are fed directly
to the \fBfpfit\fP program, and thus should be either a \fI1\fP or a \fI0\fP; parameter-file boolean string 
values will not be translated. 
.SH AUTHOR
.nf
Dr. Kent Lindquist
Lindquist Consulting, Inc.
.fi
