.TH Fmfpfit 3P 
.SH NAME
Fmfpfit \- evproc class for computing focal-mechanisms with USGS fpfit
.SH SYNOPSIS
.nf
use Fmfpfit;

( $obj, $hashref ) = \fBnew\fP( $class,
                          "db" => $dbref,
			  "dbm" => $dbmref [, $name1, $val1 [,...]] );

\fBdisplay\fP( $obj [, @keys] );

\fBput\fP( $obj, $name1, $val1 [,...] );

@vals = \fBget\fP( $obj, @keys );

$hashref = \fBprocess_channel\fP( $obj, $trref, $flush );

$hashref = \fBprocess_station\fP( $obj, $sta, $flush );

$hashref = \fBprocess_network\fP( $obj, $flush );

.fi
.SH DESCRIPTION
The \fBFmfpfit\fP module runs within \fBorbevproc\fP(1) or \fBdbevproc\fP(1), delegating computation 
of earthquake focal-mechanisms to the U.S. Geological Survey's \fBfpfit\fP program. The \fBFmfpfit\fP assumes
the first motion measurements have already been obtained by other means, then entered into the arrival table 
of the database before invoking fpfit. Results are entered into the \fIfplane\fP table of the database. 
.SH FILES
The \fBFmfpfit\fP module creates several temporary files, including:
.nf

fpfit_in_<orid>.hyp
fpfit_out_<orid>.out
fpfit_out_<orid>.pol
fpfit_out_<orid>.stdout
fpfit_out_<orid>.sum
.fi

(where <orid> is the origin id of the hypocenter being processed) as well as a temporary database. 
All of these files reside in a temporary directory and are removed after computation is complete
unless the \fB-keeptmp\fP option is specified to \fBdbevproc\fP. 
.SH PARAMETER FILE
.SS "Explanation of parameters"
Most of the parameters are passed directly to the \fBfpfit\fP program. Please see the \fBfpfit\fP documentation for 
further information on these. The remainder are as follows:
.IP fpfit_executable
This parameter gives the name of the \fBfpfit\fP program. It may be an absolute path.
.IP fplane_algorithm
This parameter is entered into the \fIfplane\fP table's \fIalgorithm\fP field for each focal-mechanism
solution created. 
.IP fplane_auth
This parameter is entered into the \fIfplane\fP table's \fIauth\fP field for each focal-mechanism
solution created. If left blank, a value of \fIevproc:\fP followed by the username of the Unix account running
the \fBdbevproc\fP(1) or \fBorbevproc\fP(1) program will be used. 
.IP maximum_wait_time
This gives the amount of time in seconds that the evproc programs will wait for waveform data before giving up 
on a channel (this is a placeholder for future software versions which may actually use waveform data in focal-mechanism
calculation).
.IP tempdir
Intermediate results and databases will be stored in this database and removed at the end of execution
(unless the \fI-keeptmp\fP command-line argument is given to \fBdbevproc\fP(1) or \fBorbevproc\fP(1)).
.SS "Parameter File Example"
The following block of parameters should appear inside the parameter file for \fBdbevproc\fP(1) or 
\fBorbevproc\fP(1):
.nf 

fmfpfit_params &Arr{
        fpfit_executable fpfit
        fplane_algorithm fpfit
        fplane_auth
        tempdir /tmp
        maximum_wait_time 300.0
        use_radiation_pattern_weighting 0
        perform_fine_search 0
        min_magnitude 0.
        min_observations 8
        distance_cutoff_km 9999.
        presidual_cutoff_sec 100.
        incidence_angle_min_deg 0.
        incidence_angle_max_deg 180.
        strike_search_min_deg 0.
        strike_search_max_deg 360.
        strike_search_coarse_incr 20.
        strike_search_fine_incr 2.
        dip_search_min_deg 0.
        dip_search_max_deg 90.
        dip_search_coarse_incr 10.
        dip_search_fine_incr 1.
        rake_search_min_deg -180.
        rake_search_max_deg 180.
        rake_search_coarse_incr 20.
        rake_search_fine_incr 2.
        pweight_percentages .01 .10 .20 .30
}

.fi
.SH LIBRARY
use lib $ENV{ANTELOPE}/data/evproc;

.SH "SEE ALSO"
.nf
dbevproc(1), orbevproc(1), evproc(3p), Focmec(3p)
.fi
.SH "BUGS AND CAVEATS"
The required \fBfpfit\fP program is not included. It must be separately downloaded and compiled before
this \fBFmfpfit\fP module can run successfully. At the time of this writing, \fBfpfit\fP is available 
from the web-site \fIhttp://earthquake.usgs.gov/research/software/\fP.

The parameters \fIuse_radiation_pattern_weighting\fP and \fIperform_fine_search\fP are fed directly
to the \fBfpfit\fP program, and each should thus be either a \fI1\fP or a \fI0\fP; parameter-file boolean string 
values will not be translated. 

This version of \fBFmfpfit\fP does not handle errors and database problems gracefully. 
.SH AUTHOR
.nf
Dr. Kent Lindquist
Lindquist Consulting, Inc.
.fi
