.TH FOCMEC 3P 
.SH NAME
Focmec \- Focal-mechanism superclass for evproc-based generalized event processing
.SH SYNOPSIS
.nf
.fi
.SH DESCRIPTION
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
MT-Safe ?
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
Dr. Kent Lindquist
Lindquist Consulting, Inc.
.fi
