DATADIR= php/images

DATA= roadnet_bottom_line.gif \
      roadnet_logo_bkgrd.gif  \
      roadnet_logo.jpg  \
      roadnet_page_bkgrd.gif \
      roadnet_sorry.gif

MAN3H= rtimbank.3h

include $(ANTELOPEMAKE)
