DATADIR=responses
DATA=SSA2_50 dummy GEOS_100 SCSN_20 SSR1_50 uwiseismic unkn_vel fir_dummy \
	 gsv_111_10mm sm6-b BH1 \
	 seismonitor lp12_8hz lp8_8hz \
	 sm2_aa_128sps sm2_aa_256sps

                       
SUBDIR=/contrib
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
