DATADIR=doc/refguides/user
DATA= \
	cd1.ref \
	commands.ref \
	database_processing.ref \
	datascope.ref \
	foreign.ref \
	location.ref \
	realtime.ref \
	user.ref \
	user0.ref \
	waveform_analysis.ref 

include $(ANTELOPEMAKE)
