DATADIR=responses
DATA=README_quanterra F64C F64CM  F72B F72BM F96C F96CM \
     F260 F260M FS2D5 FS2D5M  F400M F640M MP LP ULP VLP
                           
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
