DATADIR=schemas
DATA= Acronyms1.2 \
      dbcluster0.5 \
      dbcluster0.6 \
      dbcluster0.7 \
      dbrecenteqs1.0 \
      dbrecenteqs1.1 \
      dbrecenteqs1.2 \
      places1.2

include $(ANTELOPEMAKE)
