DATADIR= matlab/antelope/examples/demodb/response
DATA= \
	streckeisen.1 \
	streckeisen.2 \
	streckeisen.3 \
	sts-1h-vbb.206 \
	sts-1v.55 \
	sts2_vel_RT72A.1

CLEAN=

PACKAGE=$(ANTELOPE)/contrib
include $(ANTELOPEMAKE)

