DATADIR=instruments/dataloggers
DATA=     rt130.pf \
    rt130s.pf \
    rt24_100.pf \
    rt24_62.pf \
    rt72a-02.pf \
    rt72a-07.pf \
    rt72a-07p.pf \
    rt72a-08.pf \
    rt72a-08p.pf \
    rt97_06.pf \
    rt97_80.pf 

SUBDIR=/contrib
include $(ANTELOPEMAKE)
DIRS=
