DATADIR=instruments/dataloggers
DATA= 	qx80-90.pf \
	qx80-92.pf \
    Passcal_q330_linear.pf \
    Passcal_q330_linear_b100.pf \
    q330_linear.pf \
    q330_linear_ANF.pf \
    q330_linear_below_100.pf \
    q330_linear_below_100_ANF.pf \
    q330_linear_below_20.pf \
    q330_linear_below_40.pf \
    q330_linear_dec10.pf \
    q330_linear_ANF_dec10.pf \
    q330_linear_below_100_dec10.pf \
    q330_linear_below_100_ANF_dec10.pf \
    q330_linear_below_20_dec10.pf \
    q330_linear_below_40_dec10.pf \
    q330hr_linear.pf \
    q330hr_linear_ANF.pf \
    q330hr_linear_below_100.pf \
    q330hr_linear_below_100_ANF.pf \
    q330hr_linear_below_20.pf \
    q330hr_linear_below_40.pf \
    q4120.pf \
    q730.pf \
    qep_ANF.pf \
    qep_soh_only.pf \
    qep_with_sensors.pf \
    qep_wxt.pf \
    qep_ch1.pf \
    qep_ch2.pf \
    qep_ch3.pf 

include $(ANTELOPEMAKE)
DIRS=
