DATADIR=doc/txform/ref2mif
DATA= \
    cdeclarations.pl \
    commands.pl \
    expression.pl \
    fdeclarations.pl \
    function.pl \
    initialization.pl \
    list.pl \
    mif.pl \
    mif_pathname.pl \
    parse_cdecl.pl \
    parse_fdecl.pl \
    pythonfunctions.pl \
    section.pl \
    structures.pl

include $(ANTELOPEMAKE)

