DATADIR=matlab/antelope/antelope/@cggrid/private

DATA= $(MEXSRCS:.c=.$(MEXEXT)) 

MEXSRCS= \
	cggrid_free.c 

CLEAN= 

cflags=
fflags=
ldflags=
ldlibs= 

include $(ANTELOPE)/include/mex_antelope_makerules
