DATADIR=responses
DATA=DPG_1B DPG_1S DPG_2AIR DPG_2WATER mb2000_fil mb2000_raw \
     cmg3t_vel cmg3t_120_vel cmg3t_vel_old cmg3esp cmg3_esp_vel \
     cmg3esp_vel cmg3t.302_vel cmg5_acc cmg40t_vel  \
     episensor fba11 fba23_50 fba23_100 fba_2g_acc \
     gs13_vel hs10_vel hs10_50k_vel ks54000 \
     l4c l4c_3_vel l4c_7_vel l22_vel l22_5_vel l22_7_vel l28_vel \
     peppv_vel range_vel s6000_vel sh_vel sts2_vel
                
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
