DATADIR=responses
DATA= \
	DPG_1B \
	DPG_1S \
	DPG_2AIR \
	DPG_2WATER \
	cmg3esp* \
	cmg3t \
	cmg3t_100sec \
	cmg40t \
	cmg5 \
	episensor \
	fba11 \
	fba23_6damp_100hz \
	fba23_6damp_50hz \
	fba23_7damp_50hz \
	gs13 \
	hs10_1hz \
	hs10_2hz \
	ks54000 \
	l22 \
	l22_5damp \
	l28 \
	l4c \
	l4c_3damp \
	mb2000_fil \
	mb2000_raw \
	peppv \
	ranger \
	s6000 \
	sh \
	sts2 \
	terratech
                
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
