DATADIR=responses
DATA= \
    DPG_1B \
    DPG_1S \
    DPG_2AIR \
    DPG_2WATER \
    cmg3esp \
    cmg3t.302_vel \
    cmg3t_120_vel \
    cmg3t_vel \
    cmg3t_vel_old \
    cmg40t_vel \
    cmg5_acc \
    episensor \
    fba11 \
    fba23_100 \
    fba23_50 \
    fba_2g_acc \
    gs13_vel \
    hs10_50k_vel \
    hs10_vel \
    ks54000 \
    l22_5_vel \
    l22_7_vel \
    l22_vel \
    l28_vel \
    l4c \
    l4c_3_vel \
    l4c_7_vel \
    mb2000_fil \
    mb2000_raw \
    peppv_vel \
    range_vel \
    s6000_vel \
    sh_vel \
    sts2_vel
                
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
