DATADIR=responses
DATA= \
    FIRA100 \
    FIRA100DP \
    FIRA100S3 \
    FIRA200 \
    FIRA200DP \
    FIRA200S3 \
    FIRA250 \
    FIRA250DP \
    FIRA250S3 \
    FIRA50 \
    FIRA50DP \
    FIRBC \
    FIRBCDP \
    FIRBNC \
    FIRBNCDP \
    README_KMI_appnote39D.pdf \
    coefA2-20 \
    coefA3-50 \
    coefA4-50 \
    coefA5-50 \
    coefA5-50-s5c \
    coefB2-80 \
    coefB2-80-140 \
    coefB2C-80 \
    coefB2C-80-140 \
    coefB3-80 \
    coefB3C-80 \
    episensor \
    fba11 \
    fba23_100 \
    fba23_6damp_100hz \
    fba23_6damp_50hz \
    fba23_7damp_50hz \
    fba23_7damp_100hz \
    ranger \
    range_vel \
    sh \
    sh_vel \
    wr1_vel
                               
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
