DATADIR=responses
DATA= \
    FIRA100 \
    FIRA100DP \
    FIRA100S3 \
    FIRA200 \
    FIRA200DP \
    FIRA200S3 \
    FIRA250 \
    FIRA250DP \
    FIRA250S3 \
    FIRA50 \
    FIRA50DP \
    FIRBC \
    FIRBCDP \
    FIRBNC \
    FIRBNCDP \
    README_KMI_appnote39a.pdf \
    episensor \
    fba11 \
    fba23_6damp_100hz \
    fba23_6damp_50hz \
    fba23_7damp_50hz \
    ranger \
    sh 
                               
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
