BIN=nordic_station2db obspy_dump_mseed_hdr \
	obspy_event2db obspy_inventory2db obspy_wf2db \
	obspy_federated_metadata
PF=obspy_wf2db.pf \
   obspy_inventory2db.pf \
   obspy_event2db.pf
MAN1=nordic_station2db.1 obspy_event2db.1 obspy_wf2db.1
include $(ANTELOPEMAKE)
DIRS=
SUBDIR=/contrib
