DATADIR=responses
DATA=README_reftek cf1 cf2 cf3 RT24_62 RT24_100 RT72A_250 RT72A_06 \
     RT97_80 RT72A_2_f RT72A_2_s RT72A_4_f RT72A_4_s RT72A_5_f RT72A_5_s \
     README_reftek_RT72A-07
                       
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
