extern int gethead ( ahhed * head, FILE * file_pt );
extern int puthead ( ahhed * head, FILE * file_pt );
extern int size ( ahhed * head );
extern int tohead ( int n, FILE * file_pt );
extern int getdata ( ahhed * head, char *array, FILE * file_pt );
extern int putdata ( ahhed * head, char *array, FILE * file_pt );
extern int putrecord ( ahhed * head, char *array, FILE * file_pt );
extern int getrecord ( ahhed * head, char *array, FILE * file_pt );
extern int getrecord2 ( ahhed * head, char **array, FILE * file_pt );
extern int gogethead ( int n, ahhed * head, FILE * file_pt );
extern int gogetrecord ( int n, ahhed * head, char *array, FILE * file_pt );
extern int logger ( char *char_pt, ahhed * head_pt );
extern int out_is_tty ( void );
extern int in_is_tty ( void );
extern char * mkdatspace ( ahhed * head );
extern void get_null_head ( ahhed * hed );
extern void acpy ( char *from, char *to, unsigned int nbytes );
extern void ah_error ( char *s1, char *s2, int status );
extern int maxamp ( ahhed * head, char *data );
extern int xdr_gethead ( ahhed * head, XDR * xdrs );
extern int xdr_puthead ( ahhed * head, XDR * xdrs );
extern int xdr_tohead ( int n, XDR * xdrs );
extern int xdr_getdata ( ahhed * head, char *array, XDR * xdrs );
extern int xdr_putdata ( ahhed * head, char *array, XDR * xdrs );
extern int xdr_putrecord ( ahhed * head, char *array, XDR * xdrs );
extern int xdr_getrecord ( ahhed * head, char *array, XDR * xdrs );
extern int xdr_getrecord2 ( ahhed * head, char **array, XDR * xdrs );
extern int xdr_gogethead ( int n, ahhed * head, XDR * xdrs );
extern int xdr_gogetrecord ( int n, ahhed * head, char *array, XDR * xdrs );
extern int xdr_ahhead ( XDR * xdrsp, ahhed * ahheadp );
