DATADIR=responses
DATA=README_guralp_fir.pdf guralp_10 guralp_16 guralp_2 \
	guralp_3 guralp_4 guralp_5 guralp_8 \
	cmg3esp cmg3esp_nsn cmg3t cmg3t_100sec cmg40t cmg40t_vel cmg5 peppv
                       
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
