DATADIR=responses
DATA=README_guralp_fir.pdf guralp_10 guralp_16 guralp_2 \
	guralp_3 guralp_4 guralp_5 guralp_8 \
	cmg1t cmg3esp cmg3esp_nsn cmg3t cmg3t_100sec \
        cmg6d_2 cmg6d_4 cmg6d_5 \
	cmg40t cmg40t_vel cmg40t_1hz cmg5 cmg6t peppv
                       
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
