DATADIR=responses
DATA=  \
    README_CMG-DM24_mk2_2011_04_21.pdf \
    README_CMG-DM24_mk3_2011_04_21.pdf \
    README_Guralp_Poles_and_Zeros_2006_04_08.pdf \
    README_Guralp_Poles_and_Zeros_2011_04_24.pdf \
    README_guralp_fir_2001_03_23.pdf \
    cmg1t \
    cmg1t_100sec \
    cmg1t_120sec \
    cmg1t_360sec \
    cmg3esp \
    cmg3esp_100sec \
    cmg3esp_120sec \
    cmg3esp_30sec \
    cmg3esp_60sec \
    cmg3esp_nsn \
    cmg3t \
    cmg3t_100sec \
    cmg3t_120sec \
    cmg3t_30sec \
    cmg3t_360sec \
    cmg3t_60sec \
    cmg40t \
    cmg40t_1 \
    cmg40t_1_hi \
    cmg40t_1hz \
    cmg40t_1to100 \
    cmg40t_1sec \
    cmg40t_30sec \
    cmg40t_60sec \
    cmg40t_vel \
    cmg5 \
    cmg6d_2 \
    cmg6d_4 \
    cmg6d_5 \
    cmg6t \
    guralp_10 \
    guralp_16 \
    guralp_2 \
    guralp_3 \
    guralp_4 \
    guralp_5 \
    guralp_8 \
    peppv \
    SWA-D24-2D01 \
    SWA-D24-2D02 \
    SWA-D24-2D03 \
    SWA-D24-2D04 \
    SWA-D24-2D05 \
    SWA-D24-2D06 \
    SWA-D24-2D07 \
    SWA-D24-2D08 \
    SWA-D24-3D01 \
    SWA-D24-3D02 \
    SWA-D24-3D03 \
    SWA-D24-3D04 \
    SWA-D24-3D05 \
    SWA-D24-3D06 \
    SWA-D24-3D07 \
    SWA-D24-3D08

                       
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
