DATADIR= matlab/antelope/examples/demodb
DATA= \
	demo \
	demo.affiliation \
	demo.arrival \
	demo.assoc \
	demo.instrument \
	demo.lastid \
	demo.netmag \
	demo.network \
	demo.origin \
	demo.sensor \
	demo.site \
	demo.sitechan \
	demo.stamag \
	demo.wfdisc 

CLEAN=

include $(ANTELOPEMAKE)

