INCLUDE=seispp_io.h BasicObjectReader.h BasicObjectWriter.h \
	StreamObjectReader.h StreamObjectWriter.h
include $(ANTELOPEMAKE)
LICENSES=license_libseispp.txt
SUBDIR=/contrib
include $(ANTELOPEMAKELOCAL)
