LIB=libseispp_io.a
INCLUDE=seispp_io.h BasicObjectReader.h BasicObjectWriter.h \
	StreamObjectReader.h StreamObjectWriter.h IndexedObjectReader.h \
	StreamObjectFileIndex.h
LICENSES=license_libseispp.txt
SUBDIR=/contrib
include $(ANTELOPEMAKE)
include $(ANTELOPEMAKELOCAL)
