DATADIR=schemas
DATA=polygon1.2
MAN5=polygon1.2.5 polygon_schema.5
CLEAN= tempdb tempdb.out 

SUBDIR=/contrib
include $(ANTELOPEMAKE) 
DIRS=

#tempdb:	polygon1.1
#	printf "#\nschema polygon1.1\n" > $@
#polygon1.1.ps:dbdoc.pf macro3.3 tempdb
#	dbdoc  tempdb > tempdb.out; \
#	tbl tempdb.out |groff -Tps > $@
