EXAMPLEDIR=dbbuild-batch/austria

EXAMPLE= README \
ABTA-dbb \
ARSA-dbb \
CONA-dbb \
CSNA-dbb \
DAVA-dbb \
FETA-dbb \
KBA-dbb \
MOA-dbb \
MOTA-dbb \
MYKA-dbb \
OBKA-dbb \
RETA-dbb \
SOKA-dbb \
SQTA-dbb \
WATA-dbb \
WTTA-dbb \

include $(ANTELOPEMAKE)
