DATADIR= matlab/$(MATLAB_RELEASE)/antelope/scripts


#
# NOT HERE!!! User Matlab m-files go in data/matlab/antelope/user
#
DATA= \
	setup_antelope.m \
	array_response.m \
	tr2struct.m 
#
# NOT HERE!!! User Matlab m-files go in data/matlab/antelope/user
#

HTMLDIR= matlab/html
HTML= $(DATA:.m=.html)

CLEAN= 

include $(ANTELOPE)/local/include/mex_antelope_makerules
