DATADIR=refguides/c
DATA= \
	c.ref \
	fortran.ref \
	libPkt.ref \
	libbrttpkt.ref \
	libcoords.ref \
	libds.ref \
	liborb.ref \
	libpixaddress.ref \
	libproj.ref \
	libresponse.ref \
	libstock.ref \
	libtks.ref \
	libtr.ref \
	libtt.ref \
	libtttaup.ref \
	libxtra.ref \
	pavlis.ref

include $(ANTELOPEMAKE)
