DATADIR=doc/refguides/c
DATA= \
	c.ref \
	c0.ref \
	fortran.ref \
	libPkt.ref \
	libbrttpkt.ref \
	libbrttutil.ref \
	libmappts.ref \
	libcoords.ref \
	libds.ref \
	liborb.ref \
	libpforbstat.ref \
	libpixaddress.ref \
	libproj.ref \
	libresponse.ref \
	libstock.ref \
	libtks.ref \
	libtr.ref \
	libtt.ref \
	libtttaup.ref \
	libwffil.ref \
	libwffilave.ref \
	libwffilbrtt.ref \
	libxtra.ref \
	pavlis.ref

include $(ANTELOPEMAKE)
