.TH ATWS_MWP 3P "$Date$"
.SH NAME
atws_mwp \- Perl wrapper for PTWC Mwp routines
.SH SYNOPSIS
.nf
use atws_mwp;

.fi
.SH DESCRIPTION
The \fBatws_mwp\fP module is a perl wrapper around some Mwp calculation 
routines written by the Pacific Tsunami Warning Center.
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf

.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
atws_calc_mwp(1)
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
ATWS Staff.
.fi
