DATADIR=doc/refguides/tables
DATA= \
	antelopemake.ref \
	environment.ref \
	hier.ref \
	projections.ref \
	datascope_constants.ref \
	datascope_expressions.ref \
	pf.ref \
	time_formats.ref \
	schemas.ref \
	tables0.ref \
	tcl_extensions.ref \
	time_format_codes.ref \
	wffilbrtt.ref \
	wffilave.ref

include $(ANTELOPEMAKE)

CLEAN=hier.ref environment.ref

hier.ref:hier.ref.id
	produce hier.ref

environment.ref:environment.ref.id
	produce environment.ref
