DATADIR=refguides/tables
DATA= \
	environment.ref \
	projections.ref \
	datascope_constants.ref \
	datascope_expressions.ref \
	time_formats.ref \
	schemas.ref \
	tcl_extensions.ref \
	time_format_codes.ref 

include $(ANTELOPEMAKE)
