DATADIR=responses
DATA= \
    Cirrus_Standard_ROM_Impulse_Responses.txt \
    iir.txt \
    Zland_hp_1.0Hz_pz \
    Zland_hp_3.0Hz_pz \
    Zland_1000 \
    Zland_1000_iir_1.0Hz \
    Zland_1000_iir_3.0Hz \
    Zland_2000 \
    Zland_2000_iir_1.0Hz \
    Zland_2000_iir_3.0Hz \
    Zland_250 \
    Zland_250_iir_1.0Hz \
    Zland_250_iir_3.0Hz \
    Zland_500 \
    Zland_500_iir_1.0Hz \
    Zland_500_iir_3.0Hz

                               
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
