.TH AMAKELOCAL 1
.SH NAME
amakelocal \- Manage connections between Antelope-contrib code and software external to Antelope
.SH SYNOPSIS
.nf
.fi
.SH DESCRIPTION
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
localmake(1), antelopemake(5)
.fi
.SH "BUGS AND CAVEATS"
The name of this program has proven to be somewhat confusing. 
.SH AUTHOR
.nf
Kent Lindquist
Lindquist Consulting, Inc.
.fi
