BIN = localmake
PF = localmake.pf

MAN1 = localmake.1
MAN5 = antelopemakelocal.5

INCLUDE = antelopemake.local

CLEAN = antelopemake.local

include $(ANTELOPEMAKE)

antelopemake.local: localmake
	localmake
