BIN = amakelocal
PF = amakelocal_proto.pf

MAN1 = amakelocal.1
MAN5 = antelopemakelocal.5

INCLUDE = antelopemake.local

CLEAN = antelopemake.local

include $(ANTELOPEMAKE)

antelopemake.local: amakelocal
	amakelocal -v
