DATADIR = instruments/nom_response

DATA  = cmg3t
DATA += loop
DATA += sts2-g1
DATA += sts2-g2
DATA += sts2-g3
DATA += sts2-g3-mod
DATA += sts2_5
DATA += sts4_b
DATA += sts5a
DATA += trillium_120
DATA += trillium_120PH
DATA += trillium_240
DATA += trillium_240_1
DATA += trillium_240_2

SUBDIR = /contrib

include $(ANTELOPEMAKE)

