.TH MATDOC 1 "$Date$"
.SH NAME
matdoc2html, matdoc2dotm, matdoc_htmlwrap \- utilities to make documentation for Matlab Antelope Toolbox
.SH SYNOPSIS
.nf
matdoc2html docfile

matdoc2dotm docfile

matdoc_htmlwrap infile outfile

.fi
.SH DESCRIPTION
These utilities, intended to be run not by hand but from a makefile, ease the 
creation of documentation for commands in the Matlab Antelope toolbox. 
.SH AUTHOR
Kent Lindquist
.\" $Id$
