.TH MATDOC 1 "$Date$"
.SH NAME
matdoc \- utilities to make documentation for Matlab Antelope Toolbox
.SH SYNOPSIS
.nf
matdoc2html docfile

matdoc2dotm docfile

matdoc_htmlwrap infile outfile

.fi
.SH DESCRIPTION
These utilities, intended to be run not by hand but from a makefile, ease the 
creation of documentation for commands in the Matlab Antelope toolbox. 
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.ft CW
.RS .2i
.RE
.ft R
.SH RETURN VALUES
.SH LIBRARY
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
Kent Lindquist
.\" $Id$
