DATADIR=refguides/scripting
DATA= \
        matlab.ref \
	perl.ref \
	php.ref \
	scripting.ref \
	tcl.ref \
	tcldb.ref \
	tclorb8.ref \
	tkBrttPlot.ref \
	tkPixmap.ref \
	tkGpl.ref \
	tkVogle.ref 

include $(ANTELOPEMAKE)
