DATADIR=doc/refguides/scripting
DATA= \
        matlab.ref \
	perl.ref \
	perlDatascope.ref \
	perlGrid.ref \
	perlHistory.ref \
	perlResponse.ref \
	perlSac.ref \
	perlScg.ref \
	perlTrace.ref \
	perlVector.ref \
	perltkBplot.ref \
	php.ref \
	python.ref \
	pythonDatascope.ref \
	pythonOrb.ref \
	pythonPkt.ref \
	pythonStock.ref \
	scripting.ref \
	scripting0.ref \
	tcl.ref \
	tcldb.ref \
	tclorb8.ref \
	tkBrttPlot.ref \
	tkPixmap.ref \
	tkGpl.ref 

include $(ANTELOPEMAKE)
