DATADIR=schemas
DATA=	iceworm1.3 \
	takeoff \
	notify1.2 \
	contacts1.0 \
	statrans1.0 \
	statrans1.1 \
	models0.4 \
	wfrecords1.0 \
	track_processing1.0 \
	references1.0 \
	registry1.0 \
	registry1.1 \
	registry1.2 \
	registry1.3 \
	sitephotos0.3 \
	Images1.0 \
	Mail1.1 \
	Mail1.2 \
	Mail1.3 \
	Mail1.4 \
	Mail1.5 \
	issues1.0 \
	Techcomp1.0 \
	Bookmarks0.1 \
	Specevents1.0 \
	Travel1.0 \
	Travel1.1 \
	Travel1.2 \
	webbullets1.0

include $(ANTELOPEMAKE)  	

# $Id$ 
