DATADIR=schemas
DATA=	iceworm1.3 \
	takeoff \
	places1.2 \
	notify1.2 \
	contacts1.0 \
	dbrecenteqs1.1 \
	dbrecenteqs1.2 \
	statrans1.0 \
	statrans1.1 \
	models0.4 \
	wfrecords1.0 \
	track_processing1.0 \
	gmt1.0 \
	registry1.0 \
	registry1.1 \
	Images1.0 \
	Mail1.1

include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
