DATADIR=refguide
DATA=\
	Expression_calculator.pf \
	Fortran.pf \
	Headers.pf \
	Matlab.pf \
	Niceplot.pf \
	Perl.pf \
	antelope_utils.pf \
	arr.pf \
	bits.pf \
	bns.pf \
	bplottcl_init.pf \
	cmdline.pf \
	coords.pf \
	db.pf \
	dbtcl_init.pf \
	elog.pf \
	fortran_coords.pf \
	fortran_db.pf \
	fortran_error_handling.pf \
	fortran_general_utils.pf \
	fortran_seismic_info.pf \
	general_utils.pf \
	genloc.pf \
	orb.pf \
	orbtcl_init.pf \
	pf.pf \
	pf_.pf \
	response.pf \
	seismic_info.pf \
	stbl.pf \
	tbl.pf \
	time.pf \
	tks.pf \
	tr.pf \
	waveforms.pf 

include $(ANTELOPEMAKE)
