.TH LIBWORMDS 3 "$Date$"
.SH NAME
libwormds \- Iceworm routines connecting Antelope and Earthworm
.SH SYNOPSIS
.nf
void chdir_ewparams ( char *program );

size_t datasize ( char *type );

int GetDiskAvail_Anydisk ( char *disk, unsigned *DiskAvail );

int get_null_ak_ahhead ( ak_ahhed *hed );

int lookup_network ( char *sitedb, char *network );

STACHAN * lookup_stachan ( char *sta, char *chan );

int read_site_db ( char *dbname );

int save_waveform_data ( 
		char *format, FILE *fp, int nsamp, char *datatype, 
		DataPtr data );

int save_waveform_header ( 
		char *format, FILE *fp, STACHAN *stachan, double ts, 
		int nsamp, double samprate, char *datatype );

int SocketConnect ( int *sd );

int station_in_network ( char *sta );

int subset_for_network ( void );

void units_to_segtype ( char *units, char *segtype );

int wave_client_buf_to_float ( 
		char *datatype, int nsamp, DataPtr *data );

int wave_client_get_menu ( int *nstachans, WSEntry **menu );

int wave_client_get_pin_segments ( 
		int pin, double reqs, double reqe, 
		char *datatype, DataPtr *data, 
		int *nseg, TraceSegment **tseg );

int wave_client_get_stachan_segments ( 
		char *sta, char *chan, char *net, double reqs, 
		double reqe, char *datatype, DataPtr *data, 
		int *nseg, TraceSegment **tseg );

int wave_client_pin_to_buf ( 
		int pin, double reqs, double reqe, int gapflag, 
		double *ts, int *nsamp, double *samprate, char *datatype,
		DataPtr *data );

int wave_client_pin_to_file ( 
		int pin, double reqs, double reqe, int gapflag, 
		char *pathfile, int append, int *foff, double *ts, 
		int *nsamp, double *samprate, char *datatype );

int wave_client_stachan_to_buf ( 
		char *sta, char *chan, char *net, double reqs, 
		double reqe, int gapflag, double *ts, int *nsamp, 
		double *samprate, char *datatype, DataPtr *data );

int wave_client_stachan_to_file ( 
		char *sta, char *chan, char *net, double reqs, 
		double reqe, int gapflag, char *pathfile, int append, 
		int *foff, double *ts, int *nsamp, double *samprate,
		char *datatype );

int write_ak_ah ( int output_fd, ak_ahhed *ah );

int write_sac_header ( FILE *outfile, sac_t *sach );

.fi
.SH DESCRIPTION
These routines are used in several Iceworm modules and link both 
to Earthworm and Antelope code.
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.ft CW
.in 2c
.nf
.fi
.in
.ft R
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
libwormutil(3), libwormsol(3)
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
Kent Lindquist
Geophysical Institute 
University of Alaska
.fi
.\" $Id$
