DATADIR=responses
DATA= sts1 \
	old_sts2 \
	old_sts2_vel \
	sts2_g1 \
	sts2_g2 \
	sts2_g3 \
        sts2.5  \
	STS-2_sn_response.pdf \
	STS-2.5-HF-Zeroes-Poles.pdf
                       
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
