
DATA = \
	balerlist \
	balerproc \
	calplot \
	calib_request \
	dlcmd_cal \
	dlevent \
	gsnspec \
	q330_calibration_weblog \
	qctests \
	qgrid \
	replayed \
	rrdcache \
	rrdgraph \
	rsyncbaler \
	sitephotos \
	stabaler \
	staq330 \
	wfoffset \
	wfsrb \
	windturbine \
	tortrk

DATADIR = schemas/css3.0.ext

SUBDIR=/contrib
include $(ANTELOPEMAKE)
