
DATA = \
	balerlist \
	dlcmd_cal \
        dlevent \
	gsnspec \
	q330_calibration_weblog \
	qctests \
	qgrid \
	replayed \
	rrdcache \
	rrdgraph \
	rsyncbaler \
	sitephotos \
	wfoffset \
	wfsrb

DATADIR = schemas/css3.0.ext

include $(ANTELOPEMAKE)
