
DATA = \
	comm \
	deployment \
	dlevent \
	gsnspec \
	newcomm \
	qctest \
	qgrid \
	replayed \
	rrdcache \
	rrdgraph \
	sitephotos \
	wfoffset \
	wfsrb

DATADIR = schemas/css3.0.ext

include $(ANTELOPEMAKE)
