DATADIR=responses
DATA= abalones_filtered_c1 \
      abalones_filtered_c2 \
      lch_4_f1 \
      lch_4_f2  \
      lch_4_sinc2 \
      lch_4_sinc2_4 \
      lch_4_sinc3_4 \
      lch_4_sinc3_6 \
      lch_4_sinc1 \
      lch_4_sinc2_3 \
      lch_4_sinc3 \
      lch_4_sinc3_5


include $(ANTELOPEMAKE)
