DATADIR=responses
DATA= \
    gd1_fir1 \
    gd1_fir2 \
    gd1_fir3 \
    gd2_40_fir1 \
    gd2_40_fir2 \
    spd_fir1 \
    spd_fir2 \
    yka-bb_fir1 \
    yka-bb_fir2 \
    yka-hf_fir1 \
    yka-hf_fir2 \
    yka-sp_fir1 \
    yka-sp_fir2

include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
