DATADIR=responses
DATA= \
    gd1_fir1 \
    gd1_fir2 \
    gd1_fir3 \
    gd1_preamp \
    gd2_fir1_100 \
    gd2_fir1_20 \
    gd2_fir1_40 \
    gd2_fir2_100 \
    gd2_fir2_40 \
    gd2_firz_100 \
    gd2_firz_20 \
    gd2_firz_40 \
    gd2_preamp \
    ia_500ug \
    ia_50ug  \
    ia_fir   \
    ia_preamp \
    spd_fir1 \
    spd_fir2 \
    spd_preamp \
    yka_bb_fir1 \
    yka_bb_fir2 \
    yka_hf_fir1 \
    yka_hf_fir2 \
    yka_hf_preamp \
    yka_sp_fir1 \
    yka_sp_fir2 \
    yka_sp_preamp

include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
