DATADIR= matlab/$(MATLAB_RELEASE)/antelope/user
DATA= \
	trdisp.m \
	dbcentral_dbnames.m

HTMLDIR= matlab/html
HTML= $(DATA:.m=.html)

CLEAN= 

include $(ANTELOPE)/local/include/mex_antelope_makerules
