DATADIR=instruments/dataloggers
DATA=     etna.pf \
    etna2_acausal.pf \
    etna2_causal.pf \
    k2_whitney_c.pf \
    k2_whitney_nc.pf \
    makalu_c.pf \
    makalu_nc.pf  \
    rock_acausal_10.pf \
    rock_acausal_40.pf \
    rock_acausal_5.pf \
    rock_causal_10.pf \
    rock_causal_40.pf \
    rock_causal_5.pf


SUBDIR=/contrib
include $(ANTELOPEMAKE)
DIRS=
