
DATADIR=icons


DATA=  ANZA-logo-small.png \
       google_map_anza_icon.png \
       green_star_nooutline.png \
       orange_star_nooutline.png \
       purple_star_nooutline.png \
       red_star_nooutline.png \
       red_triangle.png \
       vsm_red_circle.png \
       wht_triangle.png \
       yel_triangle.png \
       yellow_star_nooutline.png

SUBDIR=/contrib
include $(ANTELOPEMAKE)

