DATADIR=responses
DATA= trident_1000sps_fir1    \
      trident_1000sps_fir2    \
      trident_1000sps_fir3    \
      trident_100sps_fir1    \
      trident_100sps_fir2    \
      trident_100sps_fir3    \
      trident_10sps_fir1    \
      trident_10sps_fir2    \
      trident_10sps_fir3    \
      trident_10sps_fir4    \
      trident_120sps_fir1    \
      trident_120sps_fir2    \
      trident_120sps_fir3    \
      trident_120sps_fir4    \
      trident_200sps_fir1    \
      trident_200sps_fir2    \
      trident_200sps_fir3    \
      trident_20sps_fir1    \
      trident_20sps_fir2    \
      trident_20sps_fir3    \
      trident_20sps_fir4    \
      trident_40sps_fir1    \
      trident_40sps_fir2    \
      trident_40sps_fir3    \
      trident_40sps_fir4    \
      trident_500sps_fir1    \
      trident_500sps_fir2    \
      trident_500sps_fir3    \
      trident_50sps_fir1    \
      trident_50sps_fir2    \
      trident_50sps_fir3    \
      trillium_120          \
      trillium_240          \
      trillium_40           \
      Trillium40_UserGuide_responseinfo.pdf \
      Trillium120P_UserGuide_responseinfo.pdf \
      Trillium240_UserGuide_responseinfo.pdf
                       
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
