# for the present, this empty Makefile just prevents errors
# during makes.  However, it could be that the dbbuild batch files
# should be installed somewhere, perhaps under $ANTELOPE/examples/dbbuild-batch
# In that case, subdirectories should have Makefile's which contain
# EXAMPLE and EXAMPLEDIR parameters, e.g.:

# EXAMPLEDIR=dbbuild-batch/usarray
# EXAMPLE=TA_I30A



include $(ANTELOPEMAKE)
