DATADIR=instruments/dataloggers
DATA=     cmg6d.pf \
    dm24_mk1.pf \
    dm24_mk2.pf \
    dm24_mk3.pf \
    dm24_mk3_var_gain_x1.pf \
    dm24_mk3_var_gain_x2.pf \
    dm24_mk3_var_gain_x4.pf \
    dm24_mk3_var_gain_x8.pf \
    dm24_mk3_var_gain_x16.pf \
    dm24_mk3_var_gain_x32.pf \
    dm24_mk3_var_gain_x64.pf \
    peppv.pf \
    peppv_classic.pf 

SUBDIR=/contrib
include $(ANTELOPEMAKE)
DIRS=
