DATADIR=instruments/dataloggers
DATA= hrd24.pf \
	qx80-90.pf \
	qx80-92.pf \
	\
    LC2000L.pf \
    Passcal_q330_linear.pf \
    Passcal_q330_linear_b100.pf \
    cmg6d.pf \
    dm24.pf \
    etna.pf \
    gd1.pf \
    gd2-v21.pf \
    k2_whitney_c.pf \
    k2_whitney_nc.pf \
    makalu_c.pf \
    makalu_nc.pf \
    parosci.pf \
    peppv.pf \
    peppv_classic.pf \
    q330_linear.pf \
    q330_linear_ANF.pf \
    q330_linear_below_100.pf \
    q330_linear_below_100_ANF.pf \
    q330_linear_below_20.pf \
    q330_linear_below_40.pf \
    q330hr_linear.pf \
    q330hr_linear_ANF.pf \
    q330hr_linear_below_100.pf \
    q330hr_linear_below_100_ANF.pf \
    q330hr_linear_below_20.pf \
    q330hr_linear_below_40.pf \
    q4120.pf \
    q730.pf \
    rt130.pf \
    rt24_100.pf \
    rt24_62.pf \
    rt72a-02.pf \
    rt72a-07.pf \
    rt72a-07p.pf \
    rt72a-08.pf \
    rt72a-08p.pf \
    rt97_06.pf \
    rt97_80.pf \
    spd_L4.pf \
    spd_S13.pf \
    trident.pf \
    unknown.pf \
    uwi_hg.pf \
    uwi_lg.pf \
    yka-bb.pf \
    yka-hf.pf \
    yka-sp.pf 

include $(ANTELOPEMAKE)
DIRS=
