DATADIR=responses
DATA= \
	chaparral_25  \
    hyperion \
    ifs_3000 \
	mb2000_fil \
	mb2000_raw \
	ncpa  \
	setra278  \
	setra278HA  \
	setra278offset  \
	validyne 
SUBDIR=/contrib
include $(ANTELOPEMAKE)  	
DIRS=

# $Id$ 
