.TH PHPDB 3 "$Date$"
.SH NAME
phpdb \- Datascope interface for PHP 
.SH SYNOPSIS
.nf

<?php
	dl('Datascope.so');
?>

.fi
.SH DESCRIPTION

The Datascope interface for PHP is under development, intended to 
parallel the perl interface to Datascope. For information 
contact kent@lindquistconsulting.com.

.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.ft CW
.in 2c
.nf
#!/bin/sh
exec /usr/local/bin/php -f $0

<?php
if(!extension_loaded('Datascope')) {
	dl('Datascope.so');
}
$module = 'Datascope';
$functions = get_extension_funcs($module);
echo "Functions available in the test extension:<br>\n";
foreach($functions as $func) {
    echo $func."<br>\n";
}
echo "<br>\n";

$mydb =dbopen( "/opt/antelope/data/db/demo/demo", "r" );

$mydb = dbprocess( $mydb, "dbopen origin", "dbsubset ml > 3" );
echo "table has ", dbnrecs( $mydb ), " records after subset\n";

$mydb[3] = 0;
list( $lat, $lon, $ndef, $auth, $lddate ) =
    dbgetv( $mydb, "lat", "lon", "ndef", "auth", "lddate" );

echo "$lat, $lon, $ndef, $auth, $lddate\n";

$moo = dbex_eval( $mydb, "lat + lon" );

echo var_dump( $moo ), "\n";

$moo = dbquery( $mydb, "dbVIEW_TABLES" );
echo var_dump( $moo ), "\n";

?>
.fi
.in
.ft R
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
perldb(3P)
.fi
.SH "BUGS AND CAVEATS"

WARNING: This is an unfinished prototype!! 

.SH AUTHOR
.nf
Kent Lindquist 
Lindquist Consulting
.fi
.\" $Id$
