'\" te
.TH WEBDBE 3 "$Date$"
.SH NAME
webdbe \- HTTP (web) interface to dbe
.SH SYNOPSIS
.nf
exact command (bold), options (square brackets bold, use | to separate 
alternative options), arguments (square brackets italics)
.fi
.SH DESCRIPTION
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
MT-Safe ?
.SH DIAGNOSTICS
.SH "SEE ALSO"
dbe(1) 
dbhelp(1) 
dbintro(3)
.nf
.fi
.SH "BUGS AND CAVEATS"
Currently only one subset at a time works. Subsets of a subset do not
define a correct query. Sort function does not work any more. Removed
menubar at the top of each page as the functionality does not exist.
.SH AUTHOR
Robert Newman and Kent Lindquist
.\" $Id$
